version: '3.7'
services:
 stockssys-code:
  build:
   context: ./
   dockerfile: Dockerfile
  ports:
   - 8200:80
  volumes:
   - ./code-dev:/var/www
   - ./code-dev/public:/var/www/html
  networks:
   agem_dev_net:
    ipv4_address: 173.23.100.20
volumes:
 code-dev:
networks:
 agem_dev_net:
  driver: bridge
  ipam:
   driver: default
   config:
    -
     subnet: 173.23.100.0/24
